title: "プロジェクト・マネジャーが知るべき 97 のこと"
summary: "通称「きのこ本」とよばれるオライリー発行の書籍群があります。\nこれらの書籍は CC-by-3.0 などでライセンスされており、著者名を明記すればコピー/配布や改変が自由にできます（商用利用も可能）。\nそこで、勝手に電子書籍化（非公式版）を作っています。\n詳細は https://github.com/yoshi389111/kinokobooks まで"
topics: ["プロジェクトマネージャー", "きのこ本"]
published: true
price: 0
toc_depth: 1
chapters:
  - mngr-001
  - mngr-002
  - mngr-003
  - mngr-004
  - mngr-005
  - mngr-006
  - mngr-007
  - mngr-008
  - mngr-009
  - mngr-010
  - mngr-011
  - mngr-012
  - mngr-013
  - mngr-014
  - mngr-015
  - mngr-016
  - mngr-017
  - mngr-018
  - mngr-019
  - mngr-020
  - mngr-021
  - mngr-022
  - mngr-023
  - mngr-024
  - mngr-025
  - mngr-026
  - mngr-027
  - mngr-028
  - mngr-029
  - mngr-030
  - mngr-031
  - mngr-032
  - mngr-033
  - mngr-034
  - mngr-035
  - mngr-036
  - mngr-037
  - mngr-038
  - mngr-039
  - mngr-040
  - mngr-041
  - mngr-042
  - mngr-043
  - mngr-044
  - mngr-045
  - mngr-046
  - mngr-047
  - mngr-048
  - mngr-049
  - mngr-050
  - mngr-051
  - mngr-052
  - mngr-053
  - mngr-054
  - mngr-055
  - mngr-056
  - mngr-057
  - mngr-058
  - mngr-059
  - mngr-060
  - mngr-061
  - mngr-062
  - mngr-063
  - mngr-064
  - mngr-065
  - mngr-066
  - mngr-067
  - mngr-068
  - mngr-069
  - mngr-070
  - mngr-071
  - mngr-072
  - mngr-073
  - mngr-074
  - mngr-075
  - mngr-076
  - mngr-077
  - mngr-078
  - mngr-079
  - mngr-080
  - mngr-081
  - mngr-082
  - mngr-083
  - mngr-084
  - mngr-085
  - mngr-086
  - mngr-087
  - mngr-088
  - mngr-089
  - mngr-090
  - mngr-091
  - mngr-092
  - mngr-093
  - mngr-094
  - mngr-095
  - mngr-096
  - mngr-097
