title: "ソフトウェアアーキテクトが知るべき 97 のこと"
summary: "通称「きのこ本」とよばれるオライリー発行の書籍群があります。\nこれらの書籍は CC-by-3.0 などでライセンスされており、著者名を明記すればコピー/配布や改変が自由にできます（商用利用も可能）。\nそこで、勝手に電子書籍化（非公式版）を作っています。\n詳細は https://github.com/yoshi389111/kinokobooks まで"
topics: ["アーキテクト", "きのこ本"]
published: true
price: 0
toc_depth: 1
chapters:
  - soft-001
  - soft-002
  - soft-003
  - soft-004
  - soft-005
  - soft-006
  - soft-007
  - soft-008
  - soft-009
  - soft-010
  - soft-011
  - soft-012
  - soft-013
  - soft-014
  - soft-015
  - soft-016
  - soft-017
  - soft-018
  - soft-019
  - soft-020
  - soft-021
  - soft-022
  - soft-023
  - soft-024
  - soft-025
  - soft-026
  - soft-027
  - soft-028
  - soft-029
  - soft-030
  - soft-031
  - soft-032
  - soft-033
  - soft-034
  - soft-035
  - soft-036
  - soft-037
  - soft-038
  - soft-039
  - soft-040
  - soft-041
  - soft-042
  - soft-043
  - soft-044
  - soft-045
  - soft-046
  - soft-047
  - soft-048
  - soft-049
  - soft-050
  - soft-051
  - soft-052
  - soft-053
  - soft-054
  - soft-055
  - soft-056
  - soft-057
  - soft-058
  - soft-059
  - soft-060
  - soft-061
  - soft-062
  - soft-063
  - soft-064
  - soft-065
  - soft-066
  - soft-067
  - soft-068
  - soft-069
  - soft-070
  - soft-071
  - soft-072
  - soft-073
  - soft-074
  - soft-075
  - soft-076
  - soft-077
  - soft-078
  - soft-079
  - soft-080
  - soft-081
  - soft-082
  - soft-083
  - soft-084
  - soft-085
  - soft-086
  - soft-087
  - soft-088
  - soft-089
  - soft-090
  - soft-091
  - soft-092
  - soft-093
  - soft-094
  - soft-095
  - soft-096
  - soft-097
