title: "日本を中心に活躍するプロジェクト・マネジャーよる知っておくべき 11 のこと"
summary: "通称「きのこ本」とよばれるオライリー発行の書籍群があります。\nこれらの書籍は CC-by-3.0 などでライセンスされており、著者名を明記すればコピー/配布や改変が自由にできます（商用利用も可能）。\nそこで、勝手に電子書籍化（非公式版）を作っています。\n詳細は https://github.com/yoshi389111/kinokobooks まで"
topics: ["プロジェクトマネージャー", "きのこ本"]
published: true
price: 0
toc_depth: 1
chapters:
  - mngr-101
  - mngr-102
  - mngr-103
  - mngr-104
  - mngr-105
  - mngr-106
  - mngr-107
  - mngr-108
  - mngr-109
  - mngr-110
  - mngr-111
