title: "ゲームクリエイターが知るべき 97 のこと 2"
summary: "通称「きのこ本」とよばれるオライリー発行の書籍群があります。\nこれらの書籍は CC-by-3.0 などでライセンスされており、著者名を明記すればコピー/配布や改変が自由にできます（商用利用も可能）。\nそこで、勝手に電子書籍化（非公式版）を作っています。\n詳細は https://github.com/yoshi389111/kinokobooks まで"
topics: ["ゲームクリエイター", "きのこ本"]
published: true
price: 0
toc_depth: 1
chapters:
  - game-201
  - game-202
  - game-203
  - game-204
  - game-205
  - game-206
  - game-207
  - game-208
  - game-209
  - game-210
  - game-211
  - game-212
  - game-213
  - game-214
  - game-215
  - game-216
  - game-217
  - game-218
  - game-219
  - game-220
  - game-221
  - game-222
  - game-223
  - game-224
  - game-225
  - game-226
  - game-227
  - game-228
  - game-229
  - game-230
  - game-231
  - game-232
  - game-233
  - game-234
  - game-235
  - game-236
  - game-237
  - game-238
  - game-239
  - game-240
  - game-241
  - game-242
  - game-243
  - game-244
  - game-245
  - game-246
  - game-247
  - game-248
  - game-249
  - game-250
  - game-251
  - game-252
  - game-253
  - game-254
  - game-255
  - game-256
  - game-257
  - game-258
  - game-259
  - game-260
  - game-261
  - game-262
  - game-263
  - game-264
  - game-265
  - game-266
  - game-267
  - game-268
  - game-269
  - game-270
  - game-271
  - game-272
  - game-273
  - game-274
  - game-275
  - game-276
  - game-277
  - game-278
  - game-279
  - game-280
  - game-281
  - game-282
  - game-283
  - game-284
  - game-285
  - game-286
  - game-287
  - game-288
  - game-289
  - game-290
  - game-291
  - game-292
  - game-293
  - game-294
  - game-295
  - game-296
  - game-297
