title: "ゲームクリエイターが知るべき 97 のこと"
summary: "通称「きのこ本」とよばれるオライリー発行の書籍群があります。\nこれらの書籍は CC-by-3.0 などでライセンスされており、著者名を明記すればコピー/配布や改変が自由にできます（商用利用も可能）。\nそこで、勝手に電子書籍化（非公式版）を作っています。\n詳細は https://github.com/yoshi389111/kinokobooks まで"
topics: ["ゲームクリエイター", "きのこ本"]
published: true
price: 0
toc_depth: 1
chapters:
  - game-101
  - game-102
  - game-103
  - game-104
  - game-105
  - game-106
  - game-107
  - game-108
  - game-109
  - game-110
  - game-111
  - game-112
  - game-113
  - game-114
  - game-115
  - game-116
  - game-117
  - game-118
  - game-119
  - game-120
  - game-121
  - game-122
  - game-123
  - game-124
  - game-125
  - game-126
  - game-127
  - game-128
  - game-129
  - game-130
  - game-131
  - game-132
  - game-133
  - game-134
  - game-135
  - game-136
  - game-137
  - game-138
  - game-139
  - game-140
  - game-141
  - game-142
  - game-143
  - game-144
  - game-145
  - game-146
  - game-147
  - game-148
  - game-149
  - game-150
  - game-151
  - game-152
  - game-153
  - game-154
  - game-155
  - game-156
  - game-157
  - game-158
  - game-159
  - game-160
  - game-161
  - game-162
  - game-163
  - game-164
  - game-165
  - game-166
  - game-167
  - game-168
  - game-169
  - game-170
  - game-171
  - game-172
  - game-173
  - game-174
  - game-175
  - game-176
  - game-177
  - game-178
  - game-179
  - game-180
  - game-181
  - game-182
  - game-183
  - game-184
  - game-185
  - game-186
  - game-187
  - game-188
  - game-189
  - game-190
  - game-191
  - game-192
  - game-193
  - game-194
  - game-195
  - game-196
  - game-197
