title: "プログラマが知るべき 97 のこと"
summary: "通称「きのこ本」とよばれるオライリー発行の書籍群があります。\nこれらの書籍は CC-by-3.0 などでライセンスされており、著者名を明記すればコピー/配布や改変が自由にできます（商用利用も可能）。\nそこで、勝手に電子書籍化（非公式版）を作っています。\n詳細は https://github.com/yoshi389111/kinokobooks まで"
topics: ["プログラマ", "きのこ本"]
published: true
price: 0
toc_depth: 1
chapters:
  - prog-001
  - prog-002
  - prog-003
  - prog-004
  - prog-005
  - prog-006
  - prog-007
  - prog-008
  - prog-009
  - prog-010
  - prog-011
  - prog-012
  - prog-013
  - prog-014
  - prog-015
  - prog-016
  - prog-017
  - prog-018
  - prog-019
  - prog-020
  - prog-021
  - prog-022
  - prog-023
  - prog-024
  - prog-025
  - prog-026
  - prog-027
  - prog-028
  - prog-029
  - prog-030
  - prog-031
  - prog-032
  - prog-033
  - prog-034
  - prog-035
  - prog-036
  - prog-037
  - prog-038
  - prog-039
  - prog-040
  - prog-041
  - prog-042
  - prog-043
  - prog-044
  - prog-045
  - prog-046
  - prog-047
  - prog-048
  - prog-049
  - prog-050
  - prog-051
  - prog-052
  - prog-053
  - prog-054
  - prog-055
  - prog-056
  - prog-057
  - prog-058
  - prog-059
  - prog-060
  - prog-061
  - prog-062
  - prog-063
  - prog-064
  - prog-065
  - prog-066
  - prog-067
  - prog-068
  - prog-069
  - prog-070
  - prog-071
  - prog-072
  - prog-073
  - prog-074
  - prog-075
  - prog-076
  - prog-077
  - prog-078
  - prog-079
  - prog-080
  - prog-081
  - prog-082
  - prog-083
  - prog-084
  - prog-085
  - prog-086
  - prog-087
  - prog-088
  - prog-089
  - prog-090
  - prog-091
  - prog-092
  - prog-093
  - prog-094
  - prog-095
  - prog-096
  - prog-097
